import { elements } from '../base';

export const renderView = () => {
	const markup = `
		ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART 
		ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART 
		ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART 
		ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART 
		ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART 
		ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART 
		ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART 
		ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART ART 
	`;

	elements.dynamicContent.insertAdjacentHTML('afterbegin', markup);
};